# Generated by Django 3.2.10 on 2022-06-19 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_auto_20220619_1654'),
        ('user', '0002_auto_20220619_0533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='news_sources',
            field=models.ManyToManyField(blank=True, to='news.Source'),
        ),
    ]
