# Generated by Django 3.2.10 on 2022-06-19 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topheadline',
            name='headline_id',
        ),
        migrations.RemoveField(
            model_name='topheadline',
            name='name',
        ),
        migrations.AlterField(
            model_name='topheadline',
            name='content',
            field=models.TextField(max_length=255),
        ),
        migrations.DeleteModel(
            name='Article',
        ),
    ]
