# Generated by Django 3.2.10 on 2022-06-19 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20220619_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topheadline',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
