# Generated by Django 3.2.10 on 2022-06-19 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_alter_topheadline_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topheadline',
            name='author',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='topheadline',
            name='title',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
