# Generated by Django 3.2.10 on 2022-06-19 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_auto_20220619_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topheadline',
            name='url',
            field=models.URLField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='topheadline',
            name='urlToImage',
            field=models.URLField(blank=True, max_length=400, null=True),
        ),
    ]
