# Generated by Django 3.2.10 on 2022-06-20 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_auto_20220619_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='topheadline',
            name='is_notified',
            field=models.BooleanField(default=False),
        ),
    ]
